fix lint

diff --git a/handlers/main.yml b/handlers/main.yml
--- a/handlers/main.yml
+++ b/handlers/main.yml
@@ -120,46 +120,58 @@
   changed_when: false
   ansible.builtin.command: >
     nohup bash -c "
-    nmcli connection reload;
+    nmcli connection reload
 
     returncode=0
+
+    # Bring connections down (reverse order)
     {% for interface in all_interfaces_changed | reverse %}
-    nmcli connection down {{ interface }};
+    nmcli connection down {{ interface }}
     {% endfor %}
 
+    # Bring connections up
     {% for interface in all_interfaces_changed %}
     if ! nmcli connection up {{ interface }}; then
-      echo \"Failed to bring up interface {{ interface }}\";
+      echo 'Failed to bring up interface {{ interface }}'
       returncode=1
-    fi;
+    fi
     {% endfor %}
 
-    echo 'Waiting for interfaces to become active and have a connected carrier';
+    echo 'Waiting for interfaces to become active and have a connected carrier'
+
     for i in {1..20}; do
       all_connected=true
+
       {% for interface in all_interfaces_changed %}
+
       if [[ '{{ interface }}' == *dummy* ]]; then
         allowed_states='UNKNOWN|UP'
       else
         allowed_states='UP'
       fi
 
-      if ! (nmcli -t -f DEVICE,STATE device status | grep -q -w '{{ interface }}:connected' && ip link show '{{ interface }}' | grep -q -E 'state ('$allowed_states')'); then
+      nm_state=\$(nmcli -t -f DEVICE,STATE device status | awk -F: '\$1==\"{{ interface }}\" {print \$2}')
+      link_state=\$(ip -o link show '{{ interface }}' | awk '{for(i=1;i<=NF;i++) if(\$i==\"state\") print \$(i+1)}')
+
+      if [[ \"\$nm_state\" != \"connected\" || ! \"\$link_state\" =~ \$allowed_states ]]; then
         all_connected=false
-        if [ $i -eq 20 ]; then
-          echo 'Interface {{ interface }} failed to become active and have a connected carrier';
+        if [ \$i -eq 20 ]; then
+          echo 'Interface {{ interface }} failed to become active and have a connected carrier'
+          echo \"nm_state=\$nm_state link_state=\$link_state allowed=\$allowed_states\"
           returncode=1
         fi
-      fi;
+      fi
+
       {% endfor %}
 
-      if $all_connected; then
-        break;
+      if \$all_connected; then
+        break
       fi
-      sleep 2;
+
+      sleep 2
     done
 
-    exit $returncode"
+    exit \$returncode"
   vars:
     ether_vlan_interfaces_changed: >
       {{ ether_interfaces_changed | select('match', vlan_interface_regex) | list }}
@@ -201,11 +213,11 @@
     nohup bash -c "
     returncode=0
     {% for interface in all_interfaces_changed | reverse %}
-    ifdown {% if ansible_os_family == 'Debian' %}--allow auto {% endif %}{{ interface }};
+    ifdown {% if ansible_facts.os_family == 'Debian' %}--allow auto {% endif %}{{ interface }};
     {% endfor %}
 
     {% for interface in all_interfaces_changed %}
-    if ! ifup {% if ansible_os_family == 'Debian' %}--allow auto {% endif %}{{ interface }}; then
+    if ! ifup {% if ansible_facts.os_family == 'Debian' %}--allow auto {% endif %}{{ interface }}; then
       echo \"Failed to bring up interface {{ interface }}\";
       returncode=1
     fi;
@@ -240,7 +252,7 @@
            bond_slave_interfaces_changed +
            ether_vlan_interfaces_changed +
            bond_master_interfaces_changed }}
-    all_interfaces_changed: "{{ all_interfaces_changed_map[ansible_os_family] }}"
+    all_interfaces_changed: "{{ all_interfaces_changed_map[ansible_facts.os_family] }}"
   when:
     - not interfaces_use_networkmanager
     - interfaces_skip_handlers | default("false") == "false"
